menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标籤: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart



footer:
  owner:
    enable: true
    since: 2018
  copyright: false

avatar:
  img: /img/tsukimi.jpg

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

