menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标籤: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

#background: "linear-gradient(-225deg, #3d91c7 0%, #dcf1f7 25%, #b9dee2 40%, #a3f6ff 78%, #5ca2cf 100%)"
#background: "linear-gradient(-225deg, #fff 0%, #bbd6e7 15%, #dcf1f7 35%, #b9dee2 50%, #cceff3 78%, #bcd5e5 100%)"
background: "linear-gradient(-225deg, #fff 0%, #d3e5f1 15%, #dcf1f7 35%, #b9dee2 50%, #cceaed 78%, #bcd5e5 100%)"
footer:
  owner:
    enable: true
    since: 2018
  copyright: false

avatar:
  #img: /img/tsukimi.jpg
  img: /img/fav.jpg
favicon: /img/tsukimi.jpg



busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

